# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using hjkl 
unbind Left
unbind Right
unbind Up
unbind Down
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes using Ctrl+hjkl 
unbind C-Left
unbind C-Right
unbind C-Up
unbind C-Down
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# don't ask for the confirmation when deleting panes
bind x kill-pane

# enable mouse mode 
set -g mouse on

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# move with hjkl in copy mode
set -g mode-keys vi

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' 

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

